name: OTA Mobile Update

on:
  workflow_dispatch:

jobs:
  ota:
    name: Create an iOS OTA Update
    runs-on: ubuntu-latest
    concurrency: mobile-ota
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: ğŸ— Setup Node
        uses: useblacksmith/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸš€ Create iOS OTA Update
        run: |
          COMMIT_MSG=$(echo "${{ github.event.head_commit.message }}" | head -n 1)
          eas update -p ios --channel production --non-interactive --message "Main - $COMMIT_MSG (commit: ${{ github.sha }})"
